version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt

  pre_build:
    commands:
      - echo Running unit tests...
      - python -m unittest discover -s tests

  build:
    commands:
      - echo Build phase complete.

artifacts:
  files:
    - application.py
    - requirements.txt
    - "**/*.py"
    
